### ISSUE TITLE
Possible to clone this repo directly on the SD card ?

### ISSUE THREAD

**Issue by incyi** [Lucaslhm/Flipper-IRDB#136]
I have a huge micro-sd card in my flipper zero. Is it possible if I clone this repo in the infrared folder ? Will that work ? 

I know that I have to take out the sd card and put it in my laptop before I can do that. Thanks. 

Maybe you can add this to the readme.md

**Comment by UberGuidoZ** [comment]
Though you can, I would recommend downloading it as a ZIP and then extracting it to the infrared folder on your SD. But, if you’re handy with git, you can clone it directly to the SD. Just make sure it’s into the infrared folder.
