### ISSUE TITLE
Invisible character

### ISSUE THREAD

**Issue by MrTiz** [Lucaslhm/Flipper-IRDB#203]
File **`Urevo_Treadmill_UR9TM0011.ir`** contains the invisible character **`U+200E`** between **`_`** and **`U`** in its name.
The folder is `Flipper-IRDB/tree/main/Miscellaneous/Urevo/`.

https://github.com/Lucaslhm/Flipper-IRDB/blob/main/Miscellaneous/Urevo/Urevo_Treadmill_%E2%80%8EUR9TM0011.ir

Please remove that character, thank you.

**Comment by UberGuidoZ** [comment]
Thank you for the note - this will be fixed momentarily and merged.
