### ISSUE TITLE
Request: Schneider TV

### ISSUE THREAD

**Issue by atao** [Lucaslhm/Flipper-IRDB#310]
Can you add code for remote [Schneider](https://www.schneiderconsumer.com/fr/categorie-produit/tv-video/) TV ?

Many thanks,

**Comment by UberGuidoZ** [comment]
Did you give these a try?

https://github.com/UberGuidoZ/Flipper-IRDB/tree/main/_Converted_/CSV/S/Schneider

If they work, please let us know the model and which file so we can move it out of the converted section. Thank you!

**Comment by atao** [comment]
I will try to test this.
