### ISSUE TITLE
It takes a really long time to download. Is this Normal???

### ISSUE THREAD

**Issue by Star300MS** [Lucaslhm/Flipper-IRDB#334]

**Comment by UberGuidoZ** [comment]
Do you mean to transfer to your Flipper SD? Do not do this through qFlipper or else it will take a long time. Use an SD adapter for your computer and transfer it directly. Shouldn't take more than a few minutes. (But will take hours through qFlipper.)

If you're speaking of a different download issue, please elaborate.

**Comment by UberGuidoZ** [comment]
Do you mean to transfer to your Flipper SD? Do not do this through qFlipper or else it will take a long time. Use an SD adapter for your computer and transfer it directly. Shouldn't take more than a few minutes. (But will take hours through qFlipper.)

If you're speaking of a different download issue, please elaborate.

**Comment by UberGuidoZ** [comment]
Closing this due to no further communication. Please feel free to reach out again if needed.
