### ISSUE TITLE
Request: add some remotes

### ISSUE THREAD

**Issue by dudu8009** [Lucaslhm/Flipper-IRDB#477]
i've captured some remotes [ir.zip](https://github.com/Lucaslhm/Flipper-IRDB/files/11263779/ir.zip)
LG hom bot.ir - for the [LG hom bot](https://www.lg.com/us/vacuum-cleaners/lg-LrV790R-robot-vacuum) robot vacuum cleaner
light.ir - for a generic lightbar from [aliexpress ](https://www.aliexpress.com/item/1005005088458033.html)

**Comment by UberGuidoZ** [comment]
Thank you. I will get them reviewed and added shortly!
