### ISSUE TITLE
invalid filenames

### ISSUE THREAD

**Issue by GottZ** [Lucaslhm/Flipper-IRDB#48]
there are several files in \_Pronto_Converted\_ and \_CSV-IRDB\_ that contain `,` in their names.

flipper doesn't really like that character in file names.

how should we deal with them? I don't want to cause a pull request with mass renaming them to something of my choice.

**Comment by UberGuidoZ** [comment]
We've been going through such a massive renaming but have not gotten to all of Pronto and CSV. Please, don't be shy about a massive rename if you'd like to help. =) Otherwise, we'll get to them as time allows. Leaving this open for now. Thank you!

**Comment by zigad** [comment]
@UberGuidoZ @GottZ I have removed all of commas from file names and replaced them with "_" or where "_" was already present just removed them. It's quite a massive rename but I think this will be helpful in future renaming of single files.

**Comment by UberGuidoZ** [comment]
Verified and merged. Thank you!
