### ISSUE TITLE
Airmax.ir question

### ISSUE THREAD

**Issue by inzel** [Lucaslhm/Flipper-IRDB#501]
I am able to use the Airmax.ir for my air conditioner and it works great. I am trying to understand the data values so I can edit the file to include a Temp_27 button. Can someone please explain to me how I can figure that out?

I really appreciate it. Thank you in advance

**Comment by UberGuidoZ** [comment]
AC units are a different beast - they are not easy to edit in the way you're speaking. [Check out this for a good read](https://blog.flipperzero.one/infrared/#what-is-wrong-with-air-conditioners).
