### ISSUE TITLE
TECHNIC_YH-32RA.ir may be a generic remote

### ISSUE THREAD

**Issue by Firstyear** [Lucaslhm/Flipper-IRDB#510]
Hi there,

I have a "generic brand" wall fan ( Click - model number is erased ) and while looking for a working remote noticed that the TECHNIC YH 32RA controls worked for it. This is because there is an off the shelf chip ( HS95104SK ) that is commonly used in these remotes for fans. The YH32RA appears to use this as well which is why it worked.

Would it be a valid proposition that the YH32RA ir file is duplicated to another generic fan profile? Alternately, could the HS95104SK name be put into the file name or file to assist people who are looking for this profile?

Thanks!

**Comment by UberGuidoZ** [comment]
Absolutely! Please feel free to rename and PR it with the make/model you've tested working.
