### ISSUE TITLE
Add Remote (JBL_5_1_Surround_Soundbar)

### ISSUE THREAD

**Issue by coolshrimp** [Lucaslhm/Flipper-IRDB#565]
i'v attached the .ir I captured for it.
[JBL_5_1_Surround_Soundbar.txt](https://github.com/Lucaslhm/Flipper-IRDB/files/12462677/JBL_5_1_Surround_Soundbar.txt)

**Comment by UberGuidoZ** [comment]
Will review and get this added properly. Thank you!

**Comment by UberGuidoZ** [comment]
https://github.com/Lucaslhm/Flipper-IRDB/commit/a1a0db394bf00d9b7974c9d3272c20eae75f27db
