### ISSUE TITLE
Convert type Parsed to type Raw

### ISSUE THREAD

**Issue by quocanhkcn2018** [Lucaslhm/Flipper-IRDB#574]
Hi all,
Based on some ".ir files", can I convert Type: Parsed into Type: Raw? and how to do it? thank you

**Comment by darmiel** [comment]
> Do you have a specific reason for this desire? That said, @darmiel did release a firmware of Unleashed at one point that only captured in raw format (mainly for testing), so if that is something you have a need for, it is possible.

This function got merged into Unleashed. If you want to force your Flipper to not decode the data, you have to enable Debug Mode in the settings and then open the Infrared app. There should be an option to capture Raw only data.
You can take a look at the PR https://github.com/DarkFlippers/unleashed-firmware/pull/273 for more information.
