### ISSUE TITLE
New IR remote for window cleaner Hobot-2S

### ISSUE THREAD

**Issue by Angel0ffDeath** [Lucaslhm/Flipper-IRDB#608]
[Hobot_2S.zip](https://github.com/Lucaslhm/Flipper-IRDB/files/13260113/Hobot_2S.zip)

Hi,
Due to some unknown reasons, was not able to open PR.
Nevertheless, attached is ir file for window cleaner Hobot-2S.
The file is recorded with Flipper Zero, but I was also able to command the device through my IR Blaster which is with openBeken (something like tasmota).  There are no NECext protocol in openBeken, but sending single byte commands with NEC protocol and correct address worked for me. This means already existing file in this repo (HOBOT.ir) should also work if you only change the address with the correct one (however I didn't tested that).
I mean sending IRSend NEC 0x1FC5 0x12 0 (the last 0 is repeats) from IRBlaster has the same effect as what Flippero zero sends by using NECext protocol, address 0x1FC5 and command in this case 0xED12. i.e. it looks only the low byte of command matters...

Hope this will be helpful. Regards.

**Comment by UberGuidoZ** [comment]
Wonderful - thank you for this. I'll get it added manually.
