### ISSUE TITLE
Add Hitachi RC49141 SmartTV remote

### ISSUE THREAD

**Issue by rickyjumb** [Lucaslhm/Flipper-IRDB#637]
Hello,
First of all, I've never submitted anything on github so please be patient if I made some mistake.
Attached should be the zipped ir file for the Hitachi RC49141 remote. In the comments of the file I added the model number of the tv I tested it on.
Thanks
[Hitachi_SmartTV_RC49141.ir.zip](https://github.com/Lucaslhm/Flipper-IRDB/files/13794194/Hitachi_SmartTV_RC49141.ir.zip)

**Comment by UberGuidoZ** [comment]
Thank you. I'll get this added correctly!
