### ISSUE TITLE
Flipper-IRDB/Projectors/RIF6/RIF6-cube-projector-parsed.ir contains trash

### ISSUE THREAD

**Issue by kdpdev** [Lucaslhm/Flipper-IRDB#702]
Flipper-IRDB/Projectors/RIF6/RIF6-cube-projector-parsed.ir contains trash
https://github.com/Lucaslhm/Flipper-IRDB/blob/main/Projectors/RIF6/RIF6-cube-projector-parsed.ir
Data from there:
```
name: Power
type: parsed
protocol: NEC
address: 00 00 00 00
command: 0x FF A2 5D
```
NEC signals are coded by 8-bits adress and 8-bits command
The 'command' field starts with unexpected '0x' byte and has 3 meaningfull bytes, i.e. 3*8bits for command and this fact is in contradiction of NEC specification.
All signals in the file have the same issue.

**Comment by UberGuidoZ** [comment]
Looks like it may have come from here:
- https://github.com/Sarah-C/RIF6_Projector_RemoteControl

I'll move it to the "Converted" section so someone can try to either recreate or test things out, but what is there is not lost. Thank you.
