### ISSUE TITLE
Add Irobot roomba RC 

### ISSUE THREAD

**Issue by gazirov** [Lucaslhm/Flipper-IRDB#744]
[Irobot_roomba600.zip](https://github.com/Lucaslhm/Flipper-IRDB/files/15178194/Irobot_roomba600.zip)

Add Irobot roomba RC 
Roomba 521
Roomba 531
Roomba 555
Roomba 564
Roomba 581
Roomba 616
Roomba 620
Roomba 630
Roomba 650
Roomba 760
Roomba 770
Roomba 776
Roomba 780
Roomba 785
Roomba 790
Roomba 865
Roomba 870
Roomba 876
Roomba 880
Roomba 886
Scooba 385
Scooba 390

**Comment by UberGuidoZ** [comment]
Done! Thank you.
