### ISSUE TITLE
philips fw750c remote

### ISSUE THREAD

**Issue by GR-noob** [Lucaslhm/Flipper-IRDB#748]
Hello.
My eng is no so good sorry. If i understand correctly is possible to a remote to be added. If yes, can be added the remote for philips fw750c please ? Or maybe the yes was to if i have a saved remote to sent it to be added. Sorry again. If is the second please delete this post.

![403517974_6776378815783808_5059453116862318768_n](https://github.com/Lucaslhm/Flipper-IRDB/assets/27872693/83cfa750-aef1-460f-8c01-78dbb7f18afe)

**Comment by UberGuidoZ** [comment]
Request merged in https://github.com/Lucaslhm/Flipper-IRDB/pull/799
