### ISSUE TITLE
Cleartouch smart whiteboards

### ISSUE THREAD

**Issue by BurningButter** [Lucaslhm/Flipper-IRDB#759]

**Comment by UberGuidoZ** [comment]
Are you looking for these or do you have them to add? If you're having an issue with one, please note which it is. The whiteboards are here: https://github.com/Lucaslhm/Flipper-IRDB/tree/main/Whiteboards

**Comment by BurningButter** [comment]
Sorry for the poor communication, this was a request but actually I did end up getting signals for that device since it wasn't listed. I'll upload those soon

**Comment by UberGuidoZ** [comment]
Awesome! Would appreciate that. Feel free to even just attach an IR here if it’s easier and we’ll get it added. Thank you.
