### ISSUE TITLE
Missing very common AC brand. (Maytag)

### ISSUE THREAD

**Issue by iluvflipperzero** [Lucaslhm/Flipper-IRDB#771]
I own a Maytag model m6x06f2a AC unit in my room and I got the AC without a remote, I tried searching everywhere for the Maytag ac IR codes in HEX or whatever form but can't find anything. Can someone please upload the file, that would be super nice :) "ive been standing up to turn on this AC for two years and just noticed it had an IR receiver".

**Comment by jaylikesbunda** [comment]
It's your lucky day!
Your AC was in the Harmony Remote db :)

(just remember to take the .txt off the file)
[MayTag_M6X06F2A.ir.txt](https://github.com/user-attachments/files/17057724/MayTag_M6X06F2A.ir.txt)

**Comment by UberGuidoZ** [comment]
Request merged in https://github.com/Lucaslhm/Flipper-IRDB/pull/799
