### ISSUE TITLE
[Q] convert codes parsed with tasmota

### ISSUE THREAD

**Issue by eadmaster** [Lucaslhm/Flipper-IRDB#772]
how can i convert codes [received via Tasmota](https://tasmota.github.io/docs/Tasmota-IR/#receiving-ir-commands)?

They follow this format:
`{"IrReceived":{"Protocol":"<value>","Bits":<value>,"Data":<value>}}`

e.g.:
`{"Protocol":"NEC","Bits":32,"Data":"0x20DF10EF"}`

**Comment by eadmaster** [comment]
just found out there is [this method](https://crankyoldgit.github.io/IRremoteESP8266/doxygen/html/classIRsend.html#ab2e1ce918e4e06b955c3d2a089ce189c)  to perform the conversion.

**Comment by UberGuidoZ** [comment]
Certainly hope to see some additions from you! =) Thank you for coming back with the answer.

**Comment by eadmaster** [comment]
For pc-side use i've made this script
https://gist.github.com/eadmaster/5c36fd467cf57f5f4025ee6b8082a600
