### ISSUE TITLE
Add Canon RC-6 universal remote

### ISSUE THREAD

**Issue by frank42hh** [Lucaslhm/Flipper-IRDB#776]
Hi,

not sure if one of the already present Canon camera remotes does contain this signal, but just in case, here's the IR file for the Canon Universal Remote RC-6.

compatible products:

EOS 5DS / 5DS R
EOS 600D
EOS 7D
EOS 450D
EOS 550D
EOS 5D Mark III
EOS 90D
EOS D30
EOS M5
EOS 10D
EOS 400D
EOS 500D
EOS 6D
EOS 700D
EOS 77D
EOS 80D
EOS 20D
EOS 750D /760D
EOS D60
EOS M3
EOS 100D
EOS 300D
EOS 5D Mark IV
EOS 650D
EOS 800D
EOS M/ 
EOS M2
EOS 350D
EOS 60D
EOS 60Da
EOS 6D Mark II
EOS 7D II
EOS 5D Mark II
EOS 70D
EOS M6
EOS M5

[Canon RC-6.ir.zip](https://github.com/user-attachments/files/16360282/Canon.RC-6.ir.zip)

**Comment by UberGuidoZ** [comment]
Thank you! I'll get it added and labeled.

**Comment by UberGuidoZ** [comment]
Done!
