### ISSUE TITLE
Same remote IR for TV GRUNDIG (existing) and the Waltham wthd 3214 B (non existing)

### ISSUE THREAD

**Issue by SullivanNagler** [Lucaslhm/Flipper-IRDB#801]
Hey,
I do not know how you think the best way to indicate the user that the TV (brand: Waltham model: WTHD3214B) is using the same remote as the GRUNDIG already in your repo. 
Thx for this usefull repo.
Sullivan

**Comment by UberGuidoZ** [comment]
It's been a difficult thing to organize... sometimes the best thing to do is to make a copy and name it in a way that will be easily found. Will get that done here! Thank you.

**Comment by UberGuidoZ** [comment]
Done! Thank you.
